/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import sun.audio.AudioPlayer;
import sun.audio.AudioStream;

/**
 *
 * @author Jose
 */
public class Gameover extends javax.swing.JFrame {

    /**
     * Creates new form Gameover
     */
    public Gameover() {
        initComponents();
        String Filename = "../assets/gameoveryeah.wav";
        InputStream in = null;
        try {
            in = new FileInputStream(Gameover.class.getResource(Filename).getFile());
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Gameover.class.getName()).log(Level.SEVERE, null, ex);
        }

        AudioStream as = null;
        try {
            as = new AudioStream(in);
        } catch (IOException ex) {
            Logger.getLogger(Gameover.class.getName()).log(Level.SEVERE, null, ex);
        }

        AudioPlayer.player.start(as);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/gameover.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 860, 493);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
