/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import bin.Player;
import bin.Savefile;
import bin.Saveutil;
import bin.Scenery;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import resources.*;

/**
 *
 * @author Jose
 */
public class Mainmenu extends javax.swing.JFrame {
    public LinkedList<Scenery> sceneries;
    /**
     * Creates new form Mainmenu
     */
    public Map m;
    public Mainmenu() {
        initComponents();
      
        sceneries = new LinkedList();
       
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        entrarbtn = new javax.swing.JButton();
        cadastrarbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        entrarbtn.setText("Carregar");
        entrarbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                entrarbtnMouseClicked(evt);
            }
        });
        getContentPane().add(entrarbtn);
        entrarbtn.setBounds(620, 490, 121, 63);

        cadastrarbtn.setText("Novo jogo");
        cadastrarbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cadastrarbtnMouseClicked(evt);
            }
        });
        getContentPane().add(cadastrarbtn);
        cadastrarbtn.setBounds(620, 390, 135, 87);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/squarequest.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrarbtnMouseClicked
        Player p = new Player();
        m = new Map(sceneries,p);
        sceneries.add(new Map1(m,p));
        sceneries.add(new Map2(m,p));
        
        
        m.changeMap(0);
        m.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_cadastrarbtnMouseClicked

    private void entrarbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entrarbtnMouseClicked
        Savefile s= Saveutil.load();
        Player p = new Player();
        p.hp = s.playerhp;
        m = new Map(sceneries,p);
       
        sceneries.add(new Map1(m,p));
        sceneries.add(new Map2(m,p));
        
        m.changeMap(s.sceneryindex);
        m.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_entrarbtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mainmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mainmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mainmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mainmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mainmenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastrarbtn;
    private javax.swing.JButton entrarbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
